### ISSUE TITLE
A possible postBuild configuration file

### ISSUE THREAD

**Issue by dou-du** [aiidalab/aiidalab-test-app-action#3]
When I try to test the widget_periodictable, I need to run additional command lines to make them shown in the Jupyter notebook.

```bash
jupyter nbextension install --py --user widget_periodictable
jupyter nbextension enable widget_periodictable --user --py
```
I am wondering that is it possible to have a postBuild configuration file (like the Binder), which runs additional custom commands in the docker container before testing.

**Comment by csadorf** [comment]
I think it would be a very bad idea to start adding custom commands to this action, simply because the whole point of the test action is to test the web application in the exact state that it would be deployed. So if we add additional commands then we can no longer guarantee that the application actually works as expected.

It is possible that I misunderstood the issue, maybe you can send me a link to the failing build so that I can understand it better and also propose an alternative solution?
